# Generated by Django 5.0.1 on 2024-05-29 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.IntegerField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
